### PR TITLE
Create Kendo.Mvc.ExternalAnnotations.xml

### LINKED ISSUE #59: Add annotations for Kendo.Mvc
I see somebody made this for Kendo.Mvc
https://github.com/Dim0N22/ResharperKendoAnnotations

Could we upstream this?
Should I contact @Dim0N22 for permission first or should I contact you for approval first?

### PR DESCRIPTION
**Pull request by leotsarev**
fixes #59 
https://github.com/Dim0N22/ResharperKendoAnnotations/issues/1

Original xml was made by @Dim0N22 and licensed after MIT license

### CODE REVIEW

**Comment by derigel23** [comment]
@leotsarev Naming is wrong - that file will not be applied to Kendo.Mvc assembly. Either folder or filename should be exact as assembly name.

**Comment by leotsarev** [comment]
@derigel23 sorry, I don't understand. 
I suppose that for foo.dll I should use foo.ExternalAnnotations.xml 
so for Kendo.Mvc.dll Kendo.Mvc.ExternalAnnotations.xml 

What I mistyped?

**Comment by derigel23** [comment]
@leotsarev File should be name named Kendo.Mvc.ExternalAnnotations.xml only if it lies near the dll itself (because Kendo.Mvc.xml is reserved for XML docs). In external annotations place - it should be named exactly as dll - then it can lies anywhere. Or it can be named any name - then parent folder should be exact as dll name). So, in your PR - either folder should be named as Kendo.Mvc or file itself should be named as Kendo.Mvc.xml.
Sorry for such complex workflow. In a near future we will allow name files *.ExternalAnnotations.xml but for backward compatibility it's still better to continue old naming convention.

**Comment by leotsarev** [comment]
Done. Sorry for mess, it definitely needs squashing. Are you fine with that or I should open PR from scratch?

**Comment by derigel23** [comment]
@leotsarev It's totally okay! Thanks for PR!

**Pull request merged**
